workflows:
  build-apk:
    name: WiFi Direct Launcher - Build & Sign APK
    max_build_duration: 30
    instance_type: linux_x2

    environment:
      vars:
        JAVA_VERSION: 17
        ANDROID_HOME: /opt/android-sdk-linux
      secure:
        # these are stored in Codemagic UI (not literally here)
        # CM_KEYSTORE: Encrypted keystore file
        # CM_KEYSTORE_PASSWORD: Keystore password
        # CM_KEY_ALIAS: Key alias
        # CM_KEY_PASSWORD: Key password

    scripts:
      - name: Accept Android licenses and install SDK packages
        script: |
          sdkmanager --licenses || true
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Auto-increment versionCode
        script: |
          echo "🔢 Incrementing versionCode..."
          VERSION_CODE=$(grep versionCode app/build.gradle | awk '{print $2}')
          NEW_VERSION_CODE=$((VERSION_CODE + 1))
          sed -i "s/versionCode .*/versionCode ${NEW_VERSION_CODE}/" app/build.gradle
          ech
