workflows:
  build-apk:
    name: WiFi Direct Launcher - Build & Sign APK
    max_build_duration: 30
    instance_type: linux

    environment:
      vars:
        JAVA_VERSION: 17
        ANDROID_HOME: /opt/android-sdk-linux
        # Secure variables must be added in Codemagic UI, NOT here:
        # CM_KEYSTORE
        # CM_KEYSTORE_PASSWORD
        # CM_KEY_ALIAS
        # CM_KEY_PASSWORD

    scripts:
      - name: Accept Android licenses and install SDK packages
        script: |
          sdkmanager --licenses || true
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Auto-increment versionCode
        script: |
          echo "🔢 Incrementing versionCode..."
          VERSION_CODE=$(grep versionCode app/build.gradle | awk '{print $2}')
          NEW_VERSION_CODE
